/**
 * Downloads the web fonts so they are served from our own origin.
 *
 * Why this exists rather than a `<link>` to fonts.googleapis.com: that link is
 * render-blocking and costs a DNS lookup, a TLS handshake and two round trips
 * to a third party before the first word of text can be painted — on exactly
 * the slow mobile networks Rekoda's merchants are on. Self-hosting turns that
 * into bytes already on the connection that fetched the page.
 *
 * SUBSETS — this is the part worth reading. Google splits each family by
 * unicode range, and the obvious call for a Nigerian product is "latin only".
 * That is wrong. Yoruba needs ẹ (U+1EB9) and ọ (U+1ECD), which sit in the
 * range Google labels `vietnamese` (U+1EA0–U+1EF9). Drop it and every Yoruba
 * business name on an invoice falls back to a mismatched glyph. Igbo and Hausa
 * are covered by latin-ext.
 *
 * Cyrillic and Greek are genuinely unused here, and are dropped.
 *
 *   node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const OUT_DIR = 'apps/web/public/fonts';
const CSS_OUT = 'apps/web/public/fonts/fonts.css';
const FAMILIES = 'family=Calistoga&family=Inter:wght@400;500;600';
/** Modern UA, or Google serves TTF — roughly twice the bytes of woff2. */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/** Ranges we actually render. See the note above about Yoruba. */
const KEEP = [
  { name: 'latin', probe: 'U+0000-00FF' },
  { name: 'latin-ext', probe: 'U+0100-02BA' },
  { name: 'yoruba-and-vietnamese', probe: 'U+0102-0103' },
];

const css = await fetch(`https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`, {
  headers: { 'User-Agent': UA },
}).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts returned ${r.status}`);
  return r.text();
});

await mkdir(OUT_DIR, { recursive: true });

const blocks = css.split('@font-face').slice(1);
const kept = [];
let dropped = 0;

for (const raw of blocks) {
  const block = `@font-face${raw.split('}')[0]}}`;
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1] ?? '';
  const subset = KEEP.find((k) => range.includes(k.probe));
  if (!subset) {
    dropped++;
    continue;
  }

  const url = block.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/)?.[1];
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'font';
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? '400';
  if (!url) continue;

  const file = `${family.toLowerCase()}-${weight}-${subset.name}.woff2`;
  const bytes = Buffer.from(
    await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()),
  );
  await writeFile(join(OUT_DIR, file), bytes);
  kept.push({
    block: block.replace(/url\([^)]+\)/, `url(/fonts/${file})`),
    file,
    size: bytes.length,
  });
}

const header = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
 *
 * Self-hosted so the first paint does not wait on a third-party origin.
 * Subsets: latin, latin-ext, and U+1EA0–1EF9 — the last one is required for
 * Yoruba (ẹ, ọ), not for Vietnamese, despite the name Google gives it.
 */\n`;
await writeFile(CSS_OUT, header + kept.map((k) => k.block).join('\n') + '\n');

const total = kept.reduce((sum, k) => sum + k.size, 0);
console.log(
  `kept ${kept.length} faces (${(total / 1024).toFixed(1)} kB), dropped ${dropped} unused subsets`,
);
for (const k of kept) console.log(`  ${k.file.padEnd(42)} ${(k.size / 1024).toFixed(1)} kB`);
